CREATE TABLE AUTORES
(
    ID              BIGINT       NOT NULL,
    NOME            VARCHAR(50)  NOT NULL,
    EMAIL           VARCHAR(60)  NOT NULL,
    DATA_NASCIMENTO  DATE         NOT NULL,
    MINI_CURRICULO   VARCHAR(300) NOT NULL,
    PRIMARY KEY (ID)
);